"""Generate docs/ADAPTERS.md from the adapter sources and the detection table.

    python scripts/gen_adapters_doc.py            # writes docs/ADAPTERS.md
    python scripts/gen_adapters_doc.py --check    # exit 1 if the file is stale

Reads, for every `extension/src/adapters/<id>/index.js`, the first comment
block (the adapter's own statement of what it handles and what it refuses)
and, from `extension/src/engine/detect/index.js`, the URL rules that name
the same system. The table is generated so it cannot drift from the code:
an adapter with no URL rule shows up here as a row that says so.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADAPTERS = ROOT / "extension" / "src" / "adapters"
DETECT = ROOT / "extension" / "src" / "engine" / "detect" / "index.js"
OUT = ROOT / "docs" / "ADAPTERS.md"

# The two folders under adapters/ that are shared helpers, not systems.
HELPERS = {
    "reopen": "Reopens a collapsed wizard section through the one Edit control the adapter itself declared, so a field inside a read-only summary card can be reached; never a guessed button, never one the submit guard refuses.",
    "url_scope": "Decides whether a multi-step fill may continue after a navigation: the URL's identity tokens (tenant, job id) must still match the approved application, or the fill stops.",
}

# Only the employer-side adapter fills a posting form rather than an application.
EMPLOYER_SIDE = {"indeed_employer"}

# Adapters whose detection rule is registered under a different id.
DETECT_ID = {"indeed_apply": "indeed", "linkedin_easy_apply": "linkedin"}

REGEX_LITERAL = re.compile(r"/\^https:\\/\\/(.+?)/i\b")


def header(path: Path) -> str:
    lines = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("//"):
            lines.append(line[2:].strip())
        elif lines:
            break
    text = " ".join(lines)
    return re.sub(r"^content/adapters/[a-z_]+\.js\s*[—-]\s*", "", text)


def first_sentences(text: str, n: int = 2) -> str:
    parts = re.split(r"(?<=[.!?])\s+", text)
    out = " ".join(parts[:n]).strip()
    return out[:1].upper() + out[1:]


def readable_host(body: str) -> str:
    """`[^/]*\\.icims\\.com\\/` -> `*.icims.com`; keeps a path the rule requires."""
    s = body.replace("\\/", "/")
    s = s.replace("(?:www\\.)?", "")
    s = s.replace("(?:\\.[a-z]{2})?", "[.region]")
    s = s.replace("[^/]*\\.", "*.")
    s = s.replace("(com|de)", "{com,de}")
    s = s.replace("\\.", ".")
    return s.rstrip("/")


def detection_rules() -> dict[str, list[str]]:
    src = DETECT.read_text(encoding="utf-8")
    starts = [(m.start(), m.group(1)) for m in re.finditer(r'\bid:\s*"([a-z_]+)"', src)]
    rules: dict[str, list[str]] = {}
    for i, (pos, aid) in enumerate(starts):
        end = starts[i + 1][0] if i + 1 < len(starts) else len(src)
        chunk = src[pos:end]
        u = chunk.find("urls:")
        if u < 0:
            continue
        f = chunk.find("fingerprint", u)
        urls = chunk[u : f if f > 0 else len(chunk)]
        hosts = [readable_host(b) for b in REGEX_LITERAL.findall(urls)]
        if hosts:
            rules.setdefault(aid, []).extend(hosts)
    return rules


def render() -> tuple[str, int]:
    rules = detection_rules()
    rows = []
    for d in sorted(p for p in ADAPTERS.iterdir() if p.is_dir()):
        aid = d.name
        if aid in HELPERS:
            continue
        hosts = rules.get(DETECT_ID.get(aid, aid), [])
        detected = ", ".join(f"`{h}`" for h in hosts) if hosts else "no URL rule yet (the heuristics run alone)"
        side = "employer posting" if aid in EMPLOYER_SIDE else "candidate application"
        rows.append((aid, detected, side, first_sentences(header(d / "index.js"), 2)))
    out = [
        "# The adapters",
        "",
        "Generated by `scripts/gen_adapters_doc.py` from the adapter headers in `extension/src/adapters/` and the",
        "URL rules in `extension/src/engine/detect/index.js`. Edit those, then regenerate; do not edit this file.",
        "",
        f"{len(rows)} system adapters and {len(HELPERS)} shared modules ship under `extension/content/adapters/`",
        f"({len(rows) + len(HELPERS)} files). Every adapter returns *fill intents* only: the engine is the one writer, and every",
        "intent passes the same guards (never a password, never a payment field, never a submit) whichever adapter planned it.",
        "",
        "## Systems",
        "",
        "| Adapter | Detected on | Side | What its own header says it handles |",
        "|---|---|---|---|",
    ]
    out += [f"| `{a}` | {h} | {s} | {w} |" for a, h, s, w in rows]
    out += ["", "## Shared modules", "", "| Module | Role |", "|---|---|"]
    out += [f"| `{k}` | {v} |" for k, v in HELPERS.items()]
    out += [
        "",
        "## When there is no adapter",
        "",
        "Detection answers `unknown` as a first-class result, and the fill runs on the heuristic ladder alone: the",
        "user's own rules for that site (options page), then label-reading heuristics that match visible label",
        "text, `autocomplete` tokens, `name` and `id` conventions and ARIA roles against the profile, then the",
        "optional local model (off by default). Everything a rung cannot claim with confidence is listed on the",
        "review screen as a guess, or left for the user. The overlay names the system it detected, or says",
        "\"an unknown system\", so the user is never told the wrong name.",
        "",
        "## Adding one",
        "",
        "1. Add a URL rule (and, if the host is shared with other products, a DOM fingerprint) to",
        "   `extension/src/engine/detect/index.js`.",
        "2. Create `extension/src/adapters/<id>/index.js` whose `plan()` returns intents for the fields the",
        "   system names stably, and leaves per-tenant fields to the heuristics. The header comment is the",
        "   contract: say what is claimed, what is refused, and what was confirmed on a live page.",
        "3. Register the shipped path in `extension/src/entries.json`, run `python scripts/build_extension.py`,",
        "   and add a fixture under `tests/ext_fixtures/` that the runners evaluate against the real files.",
        "4. Run `python scripts/gen_adapters_doc.py` so this file gains the row.",
        "",
    ]
    return "\n".join(out), len(rows)


def main() -> int:
    text, n = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("docs/ADAPTERS.md is stale: run python scripts/gen_adapters_doc.py")
            return 1
        print("docs/ADAPTERS.md is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({n} systems, {len(HELPERS)} shared modules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
